### ISSUE TITLE
Base plates not working correctly with magnets

### ISSUE THREAD

**Issue by pimlie** [ostat/gridfinity_extended_openscad#34]
- Load: https://seasick.github.io/openscad-web-gui/?https%3A%2F%2Fraw.githubusercontent.com%2Fostat%2Fgridfinity_extended_openscad%2Fmain%2Fcombined%2Fgridfinity_baseplate.scad%3F0.08751745649055198
- Change x,y size to 2,3 or something
- Change base plate options to efficient magnet base

Result:
![image](https://github.com/user-attachments/assets/a535cfbe-8919-4949-84aa-a69dbf460d60)

The cutout's of each grid base doesn't seem to be positioned correctly within the grid item itself

**Comment by ostat** [comment]
This is fixed, thanks for raising. Just remember when using the online you cant bookmark, so re click the link on the site. This is because the script is cached, and the link on the site adds a random number to bust the cache.

https://seasick.github.io/openscad-web-gui/?https%3A%2F%2Fraw.githubusercontent.com%2Fostat%2Fgridfinity_extended_openscad%2Fmain%2Fcombined%2Fgridfinity_baseplate.scad%3F0.08751745649055200

![image](https://github.com/user-attachments/assets/aaae44a3-c5af-4ed3-8343-949064879414)

**Comment by ostat** [comment]
fixed thanks
