### ISSUE TITLE
Chamber wall interfere with click label

### ISSUE THREAD

**Issue by elperepat** [ostat/gridfinity_extended_openscad#46]
As you can see, I just found out about gridfinity and your openscad version is just wonderful. My 3d printer is printing bins and grid plates full time.

I also just found out about the click labels. However, my use case for now is to have 2 vertical chambers per bins and it seems the wall continues through the click label recess.

![Chamber wall interfere with click label](https://github.com/user-attachments/assets/694019ed-ff7d-4f70-98de-eb60e78d608a)

You can reproduce by using:

Default values
width: 1
vertical chamber: 2
label style: click

Thanks for your work, I really appreciate it.

**Comment by ostat** [comment]
It would be really complicated to subtract the label from the wall due to the way its coded. 
So what I have done is allow the chamber wall to be reduced in height. This solves the issue, although not really the best way. I might one day come back and see if I can improve on this.

fixed in 5f0fe56
![image](https://github.com/user-attachments/assets/517ed3c9-5459-4b81-bf06-4737c4150dc5)
